var spritef = ["precision mediump float; \n",
	"varying vec2 UV; \n",
	"varying vec3 Normal, T, B, N; \n",
	"varying vec3 FragPos;\n",
	"varying vec3 cubeuv;\n",
	"uniform samplerCube cubemap;\n",
	"uniform sampler2D sampler;\n",
	"uniform sampler2D sampler2;\n",
	"uniform sampler2D sampler3;\n",
	"uniform vec3 viewPos;\n",
	"uniform vec3 viewDir;\n",
	"uniform bool envmap;\n",
	"uniform bool normalmapping;\n",
	"vec3 ligthDir = vec3(-0.54, -1.0, -0.5);\n",
	"void main(){ \n",
	"vec4 texture = texture2D(sampler, vec2(-UV.x, UV.y));\n",
	"if(texture.a < 0.2) discard;\n",
	"gl_FragColor.rgb = texture.rgb;\n",
	"gl_FragColor.a = 1.0;\n",
	"}\n"
	].join("\n");