var GL;
var shader;
var VBO;
var envmap = false;
var normalmapping = true;
var camPos = 0;
var deltaTime;
var rotation;
var rotSpeed = 1.0;
var cubemap, texture;
var model = new Float32Array(16);
var view = new Float32Array(16);
var projection = new Float32Array(16);
var matrix = new Float32Array(16);
var direccion = new Array(3);
var arriba = new Array(3);
var Model;
var renderer;
var Canvas;
var then = 0;
var yrot, xrot, zrot;
var rot = 0.0;
var noclip = 0;
//declaración de audios
var background = new Sound();
var math = new Sound();
var menu = new Sound();
var plop = new Sound();
var final = new Sound();